# Generated by Django 5.1 on 2024-08-15 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0003_rename_parties_contract_parts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Addendum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(help_text="Tiulo do Aditivo", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição do Aditivo", null=True
                    ),
                ),
                ("effective_date", models.DateField(help_text="Data Inicial do Aditivo")),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Contrato assoiado ao aditivo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addendums",
                        to="contracts.contract",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Addendum",
                "verbose_name_plural": "Addendums",
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["title"], name="addendums_a_title_3c4f9f_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title",), name="unique_addendums_title"
                    )
                ],
            },
        ),
    ]
