# Generated by Django 5.1 on 2024-09-30 18:17

import addendums.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addendums", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addendum",
            options={
                "ordering": ["title"],
                "verbose_name": "Aditivo",
                "verbose_name_plural": "Aditivos",
            },
        ),
        migrations.AddField(
            model_name="addendum",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Faça o upload do arquivo PDF do contrato.",
                null=True,
                upload_to=addendums.models.get_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "DOCX", "DOC"])
                ],
            ),
        ),
        migrations.AddField(
            model_name="addendum",
            name="new_end_date",
            field=models.DateField(
                blank=True, help_text="Nova data final para o contrato", null=True
            ),
        ),
    ]
