# Generated by Django 5.1 on 2024-08-19 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addendums", "0001_initial"),
        ("contracts", "0003_rename_parties_contract_parts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addendum",
            name="contract",
            field=models.ForeignKey(
                help_text="Contrato associado ao aditivo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addendums",
                to="contracts.contract",
            ),
        ),
    ]
