# Generated by Django 5.1 on 2024-08-13 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Nome da parte. Deve ser único.', max_length=255, unique=True)),
                ('address', models.CharField(help_text='Endereço da parte.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email da parte.', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Número de telefone da parte.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone deve conter entre 9 e 15 dígitos.', regex='^\\d{9,15}$')])),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='parties_par_name_645a31_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_party_name')],
            },
        ),
    ]
