# Generated by Django 5.1 on 2024-08-13 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_alter_party_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name'], 'verbose_name': 'Parte', 'verbose_name_plural': 'Partes'},
        ),
        migrations.AddField(
            model_name='party',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['name'], name='parties_par_name_645a31_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_party_email'),
        ),
    ]
