# Generated by Django 5.1 on 2024-08-13 15:05

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_alter_party_options_party_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_party_email',
        ),
        migrations.AddField(
            model_name='party',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='address',
            field=models.CharField(help_text='Endereço da parte.', max_length=255),
        ),
        migrations.AlterField(
            model_name='party',
            name='email',
            field=models.EmailField(blank=True, help_text='Email da parte.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(help_text='Nome da parte. Deve ser único.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone da parte.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone deve conter entre 9 e 15 dígitos.', regex='^\\d{9,15}$')]),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_party_name'),
        ),
    ]
