# Generated by Django 5.1 on 2024-08-27 00:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        ("folders", "0001_initial"),
        ("parts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "pdf",
                    models.FileField(
                        help_text="Faça o upload do arquivo PDF do contrato.",
                        upload_to="contracts_pdfs",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "DOCX", "DOC"]
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descrição detalhada do contrato."),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total do contrato.",
                        max_digits=40,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Número identificador do contrato.", max_length=20
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Assunto ou objeto principal do contrato.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Anotações gerais sobre o contrato.",
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Data de início do contrato.")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Data de término do contrato. Se não definido, o contrato será renovado automaticamente.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("approved", "Aprovado"),
                            ("completed", "Finalizado"),
                            ("canceled", "Cancelado"),
                            ("renewed", "Renovado"),
                        ],
                        default="draft",
                        help_text="Status atual do contrato.",
                        max_length=20,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("service", "Prestação de Serviços"),
                            ("sales", "Venda"),
                            ("rental", "Locação"),
                            ("partnership", "Parceria"),
                        ],
                        help_text="Tipo de contrato.",
                        max_length=20,
                    ),
                ),
                (
                    "lgpd",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o contrato está em conformidade com a LGPD (Lei Geral de Proteção de Dados).",
                    ),
                ),
                (
                    "automatic_renewal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o contrato será renovado automaticamente.",
                    ),
                ),
                (
                    "contains_addendum",
                    models.BooleanField(
                        default=False, help_text="Indica se o contrato contém um aditivo."
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Indica se o e-mail de notificação foi enviado.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador único para a URL do contrato.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Setor ao qual o contrato pertence.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="departments.department",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="Pasta onde o contrato está armazenado.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="folders.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Partes envolvidas no contrato.",
                        to="parts.part",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["subject"],
                "indexes": [
                    models.Index(
                        fields=["subject"], name="contracts_c_subject_9a2ede_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject",), name="unique_contract_subject"
                    )
                ],
            },
        ),
    ]
