# Generated by Django 5.1 on 2024-08-15 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="pdf",
            field=models.FileField(
                help_text="Faça o upload do arquivo PDF do contrato.",
                upload_to="contracts_pdfs",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "DOCX", "DOC"])
                ],
            ),
        ),
    ]
