# Generated by Django 5.1 on 2024-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_rename_parties_contract_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="active",
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("service", "Prestação de Serviços"),
                    ("sales", "Venda"),
                    ("rental", "Locação"),
                    ("partnership", "Parceria"),
                ],
                default=1,
                help_text="Tipo de contrato.",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Anotações gerais sobre o contrato.", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("approved", "Aprovado"),
                    ("completed", "Finalizado"),
                    ("canceled", "Cancelado"),
                    ("renewed", "Renovado"),
                ],
                default="draft",
                help_text="Status atual do contrato.",
                max_length=20,
            ),
        ),
    ]
