# Generated by Django 5.1 on 2024-08-15 14:50

import django.contrib.auth.mixins
import django.views.generic.edit
import utils.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_rename_party_part_remove_part_unique_party_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartDeleteView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                utils.mixins.DepartmentPermissionMixin,
                django.contrib.auth.mixins.LoginRequiredMixin,
                django.contrib.auth.mixins.PermissionRequiredMixin,
                django.views.generic.edit.DeleteView,
            ),
        ),
    ]
