# Generated by Django 5.1 on 2024-08-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0004_partdeleteview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartDeleteView",
        ),
    ]
