# Generated by Django 5.1 on 2024-08-14 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_party_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Party',
            new_name='Part',
        ),
        migrations.RemoveConstraint(
            model_name='part',
            name='unique_party_name',
        ),
        migrations.RenameIndex(
            model_name='part',
            new_name='parts_part_name_c99d7b_idx',
            old_name='parts_par_name_645a31_idx',
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_part_name'),
        ),
    ]
