# Generated by Django 5.1 on 2024-09-30 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("historys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalrecord",
            options={
                "ordering": ["content_type"],
                "verbose_name": "Histórico",
                "verbose_name_plural": "Históricos",
            },
        ),
        migrations.AddIndex(
            model_name="historicalrecord",
            index=models.Index(
                fields=["content_type"], name="historys_hi_content_156dde_idx"
            ),
        ),
    ]
