# Generated by Django 5.1 on 2024-08-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expirations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expiration",
            options={},
        ),
    ]
